datasources:
  default:
    connection:
      url: mongodb://127.0.0.1/steedos
    objectFiles: 
      - ./src/**
tenant:
  _id: 
  name: Steedos
  logo_url:
  background_url: 
  enable_register: true
  enable_forget_password: true
  enable_create_tenant: true
email:
  host: 
  port: 465
  username: 
  password: 
  secure: true
  from: support@steedos.com
password:
  minimum_length: 10
  lowercase: true
  number: true
  uppercase: true
  symbol: true
  policy: ^(?=.*[A-Z])(?![a-z]+$)(?![^A-Za-z0-9]+$)(?!\d+$)\S{8,}$
  policyError: 密码必须包含字符、数字和字母，并至少有一个大写字母，且不能少于8位
  notifyUserAfterPasswordChanged: false
webservices:
  steedos: http://127.0.0.1:5000/